# Generated by Django 4.2.1 on 2023-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="description",
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
