# Generated by Django 4.2.1 on 2023-07-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0002_template_description_template_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                ("model", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("token_length", models.PositiveIntegerField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plans.template"
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.templateversion",
                    ),
                ),
            ],
        ),
    ]
