# Generated by Django 4.2.1 on 2023-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateversion",
            name="token_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
