# Generated by Django 4.2.1 on 2023-07-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_response_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateversion",
            name="header",
            field=models.TextField(),
        ),
    ]
